sudo: required
services: 
  - docker

before_install:
  - docker build -t vrushab/docker-react -f Dockerfile.dev .  

script:
  - docker run -e CI=true vrushab/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-east-2-471112507447"
  bucket_path: "frontend"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
